spring:
  application:
    name: personal finance mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
app:
  jwt:
    secrets-map:
      user-secret: ${JWT_USER_SECRET}
      service-secret: ${JWT_SERVICE_SECRET}
    issuer: ITAcademy
    expiration: 1800000
server:
  port: 8082