spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/classifier_service
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  application:
    name: personal finance classifier
app:
  jwt:
    secrets-map:
          user-secret: ${JWT_USER_SECRET}
          service-secret: ${JWT_SERVICE_SECRET}
    issuer: ITAcademy
    expiration: 1800000
  clients:
    user: 'http://localhost:8081/users'
server:
  port: 8083
logging:
  level:
    root: DEBUG