spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_service
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  application:
    name: personal finance
app:
  jwt:
    user-secret: ${JWT_USER_SECRET}
    service-secret: ${JWT_SERVICE_SECRET}
    issuer: Mk_jd2_111_25
server:
  port: 8081