spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  application:
    name: personal finance

app:
  jwt:
    secret:
    issuer: Mk_jd2_111_25