spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  application:
    name: personal finance
app:
  jwt:
    secret:
    issuer: Mk_jd2_111_25
server:
  port: 8081