spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  application:
    name: personal finance cabinet
app:
  jwt:
    secret: ${JWT_SECRET}
    issuer: ITAcademy
    expiration: 1800000
  clients:
    user: 'http://localhost:8081/users'
    mail: 'http://localhost:8082/mail'
server:
  port: 8080